<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="org.k2fsa.sherpa.onnx" />
    <PackageReference Include="Whisper.net" />
    <PackageReference Include="Whisper.net.Runtime" />
    <PackageReference Include="PortAudioSharp2" />
  </ItemGroup>
</Project>
