<Project>
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <LangVersion>13.0</LangVersion>
    <TreatWarningsAsErrors>false</TreatWarningsAsErrors>
    <DigitalWifeRepositoryRoot>$(MSBuildThisFileDirectory)</DigitalWifeRepositoryRoot>
    <DigitalWifeMmdEngineAssetsDir>$(DigitalWifeRepositoryRoot)assets\mmd\engine\Resources\</DigitalWifeMmdEngineAssetsDir>
    <DigitalWifeMmdSampleDataDir>$(DigitalWifeRepositoryRoot)assets\mmd\samples\GameData\</DigitalWifeMmdSampleDataDir>
  </PropertyGroup>
</Project>
