<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
    </PropertyGroup>

    <ItemGroup>
        <Compile Include="..\Zhengyan.DigitalWife.Mmd\PmxParsing.cs" Link="PmxParsing.cs" />
        <Compile Include="..\Zhengyan.DigitalWife.Mmd\VmdParsing.cs" Link="VmdParsing.cs" />
        <Compile Include="..\Zhengyan.DigitalWife.Mmd\Helpers\BinaryReaderExtensions.cs" Link="Helpers\BinaryReaderExtensions.cs" />
    </ItemGroup>

</Project>
