<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <OutputType>Exe</OutputType>
        <AllowUnsafeBlocks>True</AllowUnsafeBlocks>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="ImGui.NET" />
        <PackageReference Include="Microsoft.CodeAnalysis.CSharp.Scripting" />
        <PackageReference Include="Silk.NET.OpenGLES.Extensions.ImGui" />
        <ProjectReference Include="..\..\src\Zhengyan.DigitalWife.Audio.PortAudio\Zhengyan.DigitalWife.Audio.PortAudio.csproj" />
        <ProjectReference Include="..\..\src\Zhengyan.DigitalWife.GameProjects\Zhengyan.DigitalWife.GameProjects.csproj" />
        <ProjectReference Include="..\..\src\Zhengyan.DigitalWife.Llm.OpenAI\Zhengyan.DigitalWife.Llm.OpenAI.csproj" />
        <ProjectReference Include="..\..\src\Zhengyan.DigitalWife.Mmd.Game\Zhengyan.DigitalWife.Mmd.Game.csproj" />
        <ProjectReference Include="..\..\src\Zhengyan.DigitalWife.RealtimeVoice.Client\Zhengyan.DigitalWife.RealtimeVoice.Client.csproj" />
        <ProjectReference Include="..\..\src\Zhengyan.DigitalWife.Speech.SherpaOnnx\Zhengyan.DigitalWife.Speech.SherpaOnnx.csproj" />
    </ItemGroup>

    <ItemGroup>
        <None Include="$(DigitalWifeMmdEngineAssetsDir)**\*">
            <Link>Resources\%(RecursiveDir)%(Filename)%(Extension)</Link>
            <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
        </None>
        <None Include="..\..\assets\mmd\samples\GameData\Logo\logo.png">
            <Link>Resources\Logo\logo.png</Link>
            <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
        </None>
    </ItemGroup>

</Project>
